# Main translation file for Notedeck
# This file contains common UI strings used throughout the application
# Auto-generated by extract_i18n.py - DO NOT EDIT MANUALLY

# Regular strings

# Profile about/bio field label
About_00c0 = {"["}Àbóút{"]"}

# Column title for account management
Accounts_f018 = {"["}Àççóúñts{"]"}

# Button label to add a relay
Add_269d = {"["}Àdd{"]"}

# Label for add column button
Add_47df = {"["}Àdd{"]"}

# Button label to add a different wallet
Add_a_different_wallet_that_will_only_be_used_for_this_account_de8d = {"["}Àdd à dífféréñt wàllét thàt wíll óñly bé úséd fór thís àççóúñt{"]"}

# Error message for missing wallet
Add_a_wallet_to_continue_d170 = {"["}Àdd à wàllét tó çóñtíñúé{"]"}

# Button label to add a new account
Add_account_1cfc = {"["}Àdd àççóúñt{"]"}

# Column title for adding new account
Add_Account_d06c = {"["}Àdd Àççóúñt{"]"}

# Column title for adding algorithm column
Add_Algo_Column_0d75 = {"["}Àdd Àlgó Çólúmñ{"]"}

# Column title for adding new column
Add_Column_c764 = {"["}Àdd Çólúmñ{"]"}

# Column title for adding new deck
Add_Deck_fabf = {"["}Àdd Déçk{"]"}

# Column title for adding external notifications column
Add_External_Notifications_Column_41ae = {"["}Àdd Éxtérñàl Ñótífíçàtíóñs Çólúmñ{"]"}

# Column title for adding hashtag column
Add_Hashtag_Column_ebf4 = {"["}Àdd Hàshtàg Çólúmñ{"]"}

# Column title for adding last notes column
Add_Last_Notes_Column_bbad = {"["}Àdd Làst Ñótés Çólúmñ{"]"}

# Column title for adding notifications column
Add_Notifications_Column_79f8 = {"["}Àdd Ñótífíçàtíóñs Çólúmñ{"]"}

# Button label to add a relay
Add_relay_269d = {"["}Àdd rélày{"]"}

# Button label to add a wallet
Add_Wallet_d1be = {"["}Àdd Wàllét{"]"}

# Title for algorithmic feeds column
Algo_2452 = {"["}Àlgó{"]"}

# Description for algorithmic feeds column
Algorithmic_feeds_to_aid_in_note_discovery_d344 = {"["}Àlgóríthmíç fééds tó àíd íñ ñóté dísçóvéry{"]"}

# Label for zap amount input field
Amount_70f0 = {"["}Àmóúñt{"]"}

# Label for appearance settings section
Appearance_4c7f = {"["}Àppéàràñçé{"]"}

# Button to send message to Dave AI assistant
Ask_b7f4 = {"["}Àsk{"]"}

# Placeholder text for Dave AI input field
Ask_dave_anything_33d1 = {"["}Àsk dàvé àñythíñg...{"]"}

# Profile banner URL field label
Banner_52ef = {"["}Bàññér{"]"}

# Beta version label
BETA_8e5d = {"["}BÉTÀ{"]"}

# Broadcast the note to all connected relays
Broadcast_fe43 = {"["}Bróàdçàst{"]"}

# Broadcast the note only to local network relays
Broadcast_Local_7e50 = {"["}Bróàdçàst Lóçàl{"]"}

# Button label to cancel an action
Cancel_ed3b = {"["}Çàñçél{"]"}

# Label for cancel clear cache, Storage settings section
Cancel_fd8b = {"["}Çàñçél{"]"}

# Label for clear cache button, Storage settings section
Clear_cache_dccb = {"["}Çléàr çàçhé{"]"}

# Hover text for editable zap amount
Click_to_edit_0414 = {"["}Çlíçk tó édít{"]"}

# Column title for note composition
Compose_Note_c094 = {"["}Çómpósé Ñóté{"]"}

# Label for configure relays, settings section
Configure_relays_d156 = {"["}Çóñfígúré rélàys{"]"}

# Label for confirm clear cache, Storage settings section
Confirm_9d9d = {"["}Çóñfírm{"]"}

# Button label to confirm an action
Confirm_f8a6 = {"["}Çóñfírm{"]"}

# Status label for connected relay
Connected_f8cc = {"["}Çóññéçtéd{"]"}

# Status label for connecting relay
Connecting_6b7e = {"["}Çóññéçtíñg...{"]"}

# Title for contact list column
Contact_List_f85a = {"["}Çóñtàçt Líst{"]"}

# Column title for contact lists
Contacts_7533 = {"["}Çóñtàçts{"]"}

# Column title for last notes per contact
Contacts__last_notes_3f84 = {"["}Çóñtàçts (làst ñótés){"]"}

# Button label to copy logs
Copy_a688 = {"["}Çópy{"]"}

# Button to copy media link to clipboard
Copy_Link_dc7c = {"["}Çópy Líñk{"]"}

# Copy the unique note identifier to clipboard
Copy_Note_ID_6b45 = {"["}Çópy Ñóté ÍD{"]"}

# Copy the raw note data in JSON format to clipboard
Copy_Note_JSON_9e4e = {"["}Çópy Ñóté JSÓÑ{"]"}

# Copy the author's public key to clipboard
Copy_Pubkey_9cc4 = {"["}Çópy Púbkéy{"]"}

# Copy the text content of the note to clipboard
Copy_Text_f81c = {"["}Çópy Téxt{"]"}

# Relative time in days
count_d_b9be = {"["}{$count}d{"]"}

# Relative time in hours
count_h_3ecb = {"["}{$count}h{"]"}

# Relative time in minutes
count_m_b41e = {"["}{$count}m{"]"}

# Relative time in months
count_mo_7aba = {"["}{$count}mó{"]"}

# Relative time in seconds
count_s_aa26 = {"["}{$count}s{"]"}

# Relative time in weeks
count_w_7468 = {"["}{$count}w{"]"}

# Relative time in years
count_y_9408 = {"["}{$count}y{"]"}

# Button to create a new account
Create_Account_6994 = {"["}Çréàté Àççóúñt{"]"}

# Button label to create a new deck
Create_Deck_16b7 = {"["}Çréàté Déçk{"]"}

# Column title for custom timelines
Custom_a69e = {"["}Çústóm{"]"}

# Column title for zap amount customization
Customize_Zap_Amount_cfc4 = {"["}Çústómízé Zàp Àmóúñt{"]"}

# Column title for support page
Damus_Support_27c0 = {"["}Dàmús Súppórt{"]"}

# Label for Theme Dark, Appearance settings section
Dark_85fe = {"["}Dàrk{"]"}

# Label for deck name input field
Deck_name_cd32 = {"["}Déçk ñàmé{"]"}

# Label for decks section in side panel
DECKS_1fad = {"["}DÉÇKS{"]"}

# Label for default zap amount input
Default_amount_per_zap_399d = {"["}Défàúlt àmóúñt pér zàp:{"]"}

# Name of the default deck feed
Default_Deck_fcca = {"["}Défàúlt Déçk{"]"}

# Button label to delete a deck
Delete_Deck_bb29 = {"["}Délété Déçk{"]"}

# Tooltip for deleting a column
Delete_this_column_8d5a = {"["}Délété thís çólúmñ{"]"}

# Button label to delete a wallet
Delete_Wallet_d1d4 = {"["}Délété Wàllét{"]"}

# Profile display name field label
Display_name_f9d9 = {"["}Dísplày ñàmé{"]"}

# Domain identification message
domain___will_be_used_for_identification_b67e = {"["}"{$domain}" wíll bé úséd fór ídéñtífíçàtíóñ{"]"}

# Column title for editing deck
Edit_Deck_4018 = {"["}Édít Déçk{"]"}

# Button label to edit a deck
Edit_Deck_fd93 = {"["}Édít Déçk{"]"}

# Button label to edit user profile
Edit_Profile_49e6 = {"["}Édít Prófílé{"]"}

# Column title for profile editing
Edit_Profile_8ad4 = {"["}Édít Prófílé{"]"}

# Placeholder for hashtag input field
Enter_the_desired_hashtags_here__for_multiple_space-separated_7a69 = {"["}Éñtér thé désíréd hàshtàgs héré (fór múltíplé spàçé-sépàràtéd){"]"}

# Placeholder for relay input field
Enter_the_relay_here_1c8b = {"["}Éñtér thé rélày héré{"]"}

# Hint text to prompt entering the user's public key.
Enter_the_user_s_key__npub__hex__nip05__here_650c = {"["}Éñtér thé úsér's kéy (ñpúb, héx, ñíp05) héré...{"]"}

# Label for key input field. Key can be public key (npub), private key (nsec), or Nostr address (NIP-05).
Enter_your_key_0fca = {"["}Éñtér yóúr kéy{"]"}

# Instructions for entering Nostr credentials
Enter_your_public_key__npub___nostr_address__e_g___address____or_private_key__nsec___You_must_enter_your_private_key_to_be_able_to_post__reply__etc_48e9 = {"["}Éñtér yóúr públíç kéy (ñpúb), ñóstr àddréss (é.g. {$address}), ór prívàté kéy (ñséç). Yóú múst éñtér yóúr prívàté kéy tó bé àblé tó póst, réply, étç.{"]"}

# Label for find user button
Find_User_bd12 = {"["}Fíñd Úsér{"]"}

# Title for hashtags column
Hashtags_f8e0 = {"["}Hàshtàgs{"]"}

# Title for Home column
Home_8c19 = {"["}Hómé{"]"}

# Label for deck icon selection
Icon_b0ab = {"["}Íçóñ{"]"}

# Label for Image cache size, Storage settings section
Image_cache_size_3004 = {"["}Ímàgé çàçhé sízé:{"]"}

# Title for individual user column
Individual_b776 = {"["}Íñdívídúàl{"]"}

# Error message for invalid zap amount
Invalid_amount_6630 = {"["}Íñvàlíd àmóúñt{"]"}

# Error message for invalid key input
Invalid_key_4726 = {"["}Íñvàlíd kéy.{"]"}

# Error message for invalid Nostr Wallet Connect URI
Invalid_NWC_URI_031b = {"["}Íñvàlíd ÑWÇ ÚRÍ{"]"}

# Zap amount button for 100000 sats. Abbreviated because the button is too small to display the full amount.
k_100K_686c = {"["}100K{"]"}

# Zap amount button for 10000 sats. Abbreviated because the button is too small to display the full amount.
k_10K_f7e6 = {"["}10K{"]"}

# Zap amount button for 20000 sats. Abbreviated because the button is too small to display the full amount.
k_20K_4977 = {"["}20K{"]"}

# Zap amount button for 50000 sats. Abbreviated because the button is too small to display the full amount.
k_50K_c2dc = {"["}50K{"]"}

# Zap amount button for 5000 sats. Abbreviated because the button is too small to display the full amount.
k_5K_f7e6 = {"["}5K{"]"}

# Description for your notes column
Keep_track_of_your_notes___replies_a334 = {"["}Kéép tràçk óf yóúr ñótés & réplíés{"]"}

# Label for language, Appearance settings section
Language_e264 = {"["}Làñgúàgé:{"]"}

# Title for last note per user column
Last_Note_per_User_17ad = {"["}Làst Ñóté pér Úsér{"]"}

# Label for Theme Light, Appearance settings section
Light_7475 = {"["}Líght{"]"}

# Bitcoin Lightning network address field label
Lightning_network_address__lud16_ea51 = {"["}Líghtñíñg ñétwórk àddréss (lúd16){"]"}

# Login page title
Login_9eef = {"["}Lógíñ{"]"}

# Login button text
Login_now___let_s_do_this_5630 = {"["}Lógíñ ñów — lét's dó thís!{"]"}

# Text shown on blurred media from unfollowed users
Media_from_someone_you_don_t_follow_5611 = {"["}Médíà fróm sóméóñé yóú dóñ't fóllów{"]"}

# Tooltip for moving a column
Moves_this_column_to_another_position_0d4b = {"["}Móvés thís çólúmñ tó àñóthér pósítíóñ{"]"}

# Title for the user's deck
My_Deck_4ac5 = {"["}My Déçk{"]"}

# Label asking if the user is new to Nostr. Underneath this label is a button to create an account.
New_to_Nostr_a2fd = {"["}Ñéw tó Ñóstr?{"]"}

# NIP-05 identity field label
Nostr_address__NIP-05_identity_74a2 = {"["}Ñóstr àddréss (ÑÍP-05 ídéñtíty){"]"}

# Default username when profile is not available
nostrich_df29 = {"["}ñóstríçh{"]"}

# Status label for disconnected relay
Not_Connected_6292 = {"["}Ñót Çóññéçtéd{"]"}

# Link text for note references
note_cad6 = {"["}ñóté{"]"}

# Beta product warning message
Notedeck_is_a_beta_product__Expect_bugs_and_contact_us_when_you_run_into_issues_a671 = {"["}Ñótédéçk ís à bétà pródúçt. Éxpéçt búgs àñd çóñtàçt ús whéñ yóú rúñ íñtó íssúés.{"]"}

# Filter label for notes only view
Notes_03fb = {"["}Ñótés{"]"}

# Label for notes-only filter
Notes_60d2 = {"["}Ñótés{"]"}

# Filter label for notes and replies view
Notes___Replies_1ec2 = {"["}Ñótés & Réplíés{"]"}

# Label for notes and replies filter
Notes___Replies_6e3b = {"["}Ñótés & Réplíés{"]"}

# Column title for notifications
Notifications_d673 = {"["}Ñótífíçàtíóñs{"]"}

# Title for notifications column
Notifications_ef56 = {"["}Ñótífíçàtíóñs{"]"}

# Relative time for very recent events (less than 3 seconds)
now_2181 = {"["}ñów{"]"}

# Button label to open email client
Open_Email_25e9 = {"["}Ópéñ Émàíl{"]"}

# Instruction to open email client
Open_your_default_email_client_to_get_help_from_the_Damus_team_68dc = {"["}Ópéñ yóúr défàúlt émàíl çlíéñt tó gét hélp fróm thé Dàmús téàm{"]"}

# Label for others settings section
Others_7267 = {"["}Óthérs{"]"}

# Placeholder text for NWC URI input
Paste_your_NWC_URI_here_b471 = {"["}Pàsté yóúr ÑWÇ ÚRÍ héré...{"]"}

# Error message for missing deck name
Please_create_a_name_for_the_deck_38e7 = {"["}Pléàsé çréàté à ñàmé fór thé déçk.{"]"}

# Error message for missing deck name and icon
Please_create_a_name_for_the_deck_and_select_an_icon_0add = {"["}Pléàsé çréàté à ñàmé fór thé déçk àñd séléçt àñ íçóñ.{"]"}

# Error message for missing deck icon
Please_select_an_icon_655b = {"["}Pléàsé séléçt àñ íçóñ.{"]"}

# Button label to post a note
Post_now_8a49 = {"["}Póst ñów{"]"}

# Instruction for copying logs
Press_the_button_below_to_copy_your_most_recent_logs_to_your_system_s_clipboard__Then_paste_it_into_your_email_322e = {"["}Préss thé búttóñ bélów tó çópy yóúr móst réçéñt lógs tó yóúr systém's çlípbóàrd. Théñ pàsté ít íñtó yóúr émàíl.{"]"}

# Profile picture URL field label
Profile_picture_81ff = {"["}Prófílé píçtúré{"]"}

# Column title for quote composition
Quote_475c = {"["}Qúóté{"]"}

# Error message when quote note cannot be found
Quote_of_unknown_note_e4f0 = {"["}Qúóté óf úñkñówñ ñóté{"]"}

# Label for read-only profile mode
Read_only_82ff = {"["}Réàd óñly{"]"}

# Column title for relay management
Relays_9d89 = {"["}Rélàys{"]"}

# Label for relay list section
Relays_ad5e = {"["}Rélàys{"]"}

# Column title for reply composition
Reply_3bf1 = {"["}Réply{"]"}

# Hover text for reply button
Reply_to_this_note_f5de = {"["}Réply tó thís ñóté{"]"}

# Error message when reply note cannot be found
Reply_to_unknown_note_4401 = {"["}Réply tó úñkñówñ ñóté{"]"}

# Fallback template for replying to user
replying_to__user_15ab = {"["}réplyíñg tó {$user}{"]"}

# Template for replying to user in unknown thread
replying_to__user__in_someone_s_thread_e148 = {"["}réplyíñg tó {$user} íñ sóméóñé's thréàd{"]"}

# Template for replying to note in different user's thread
replying_to__user__s__note__in__thread_user__s__thread_daa8 = {"["}réplyíñg tó {$user}'s {$note} íñ {$thread_user}'s {$thread}{"]"}

# Template for replying to user's note
replying_to__user__s__note_ccba = {"["}réplyíñg tó {$user}'s {$note}{"]"}

# Template for replying to root thread
replying_to__user__s__thread_444d = {"["}réplyíñg tó {$user}'s {$thread}{"]"}

# Fallback text when reply note is not found
replying_to_a_note_e0bc = {"["}réplyíñg tó à ñóté{"]"}

# Hover text for repost button
Repost_this_note_8e56 = {"["}Répóst thís ñóté{"]"}

# Label for reposted notes
Reposted_61c8 = {"["}Répóstéd{"]"}

# Label for reset zoom level, Appearance settings section
Reset_62d4 = {"["}Rését{"]"}

# Heading for support section
Running_into_a_bug_1796 = {"["}Rúññíñg íñtó à búg?{"]"}

# Label for satoshis (Bitcoin unit) for custom zap amount input field
SATS_45d7 = {"["}SÀTS{"]"}

# Unit label for satoshis (Bitcoin unit) for configuring default zap amount in wallet settings.
sats_e5ec = {"["}sàts{"]"}

# Button to save default zap amount
Save_6f7c = {"["}Sàvé{"]"}

# Button label to save profile changes
Save_changes_00db = {"["}Sàvé çhàñgés{"]"}

# Column title for search page
Search_c573 = {"["}Séàrçh{"]"}

# Placeholder for search notes input field
Search_notes_42a6 = {"["}Séàrçh ñótés...{"]"}

# Search in progress message
Searching_for___query_5d18 = {"["}Séàrçhíñg fór '{$query}'{"]"}

# Description for Home column
See_notes_from_your_contacts_ac16 = {"["}Séé ñótés fróm yóúr çóñtàçts{"]"}

# Description for universe column
See_the_whole_nostr_universe_7694 = {"["}Séé thé whólé ñóstr úñívérsé{"]"}

# Button label to send a zap
Send_1ea4 = {"["}Séñd{"]"}

# Column title for app settings
Settings_7a4f = {"["}Séttíñgs{"]"}

# Label for Show source client, others settings section
Show_source_client_9e31 = {"["}Shów sóúrçé çlíéñt{"]"}

# Description for last note per user column
Show_the_last_note_for_each_user_from_a_list_50e7 = {"["}Shów thé làst ñóté fór éàçh úsér fróm à líst{"]"}

# Button label to sign out of account
Sign_out_337b = {"["}Sígñ óút{"]"}

# Title for someone else's notes column
Someone_else_s_Notes_7e5f = {"["}Sóméóñé élsé's Ñótés{"]"}

# Title for someone else's notifications column
Someone_else_s_Notifications_82e6 = {"["}Sóméóñé élsé's Ñótífíçàtíóñs{"]"}

# Description for contact list column
Source_the_last_note_for_each_user_in_your_contact_list_e157 = {"["}Sóúrçé thé làst ñóté fór éàçh úsér íñ yóúr çóñtàçt líst{"]"}

# Description for hashtags column
Stay_up_to_date_with_a_certain_hashtag_88e3 = {"["}Stày úp tó dàté wíth à çértàíñ hàshtàg{"]"}

# Description for notifications column
Stay_up_to_date_with_notifications_and_mentions_6f4e = {"["}Stày úp tó dàté wíth ñótífíçàtíóñs àñd méñtíóñs{"]"}

# Description for someone else's notes column
Stay_up_to_date_with_someone_else_s_notes___replies_464c = {"["}Stày úp tó dàté wíth sóméóñé élsé's ñótés & réplíés{"]"}

# Description for someone else's notifications column
Stay_up_to_date_with_someone_else_s_notifications_and_mentions_3473 = {"["}Stày úp tó dàté wíth sóméóñé élsé's ñótífíçàtíóñs àñd méñtíóñs{"]"}

# Description for individual user column
Stay_up_to_date_with_someone_s_notes___replies_aa78 = {"["}Stày úp tó dàté wíth sóméóñé's ñótés & réplíés{"]"}

# Description for your notifications column
Stay_up_to_date_with_your_notifications_and_mentions_e73e = {"["}Stày úp tó dàté wíth yóúr ñótífíçàtíóñs àñd méñtíóñs{"]"}

# Step 1 label in support instructions
Step_1_8656 = {"["}Stép 1{"]"}

# Step 2 label in support instructions
Step_2_d08d = {"["}Stép 2{"]"}

# Label for storage settings section
Storage_ed65 = {"["}Stóràgé{"]"}

# Column title for subscribing to external user
Subscribe_to_someone_else_s_notes_d1e9 = {"["}Súbsçríbé tó sóméóñé élsé's ñótés{"]"}

# Column title for subscribing to individual user
Subscribe_to_someone_s_notes_b3c8 = {"["}Súbsçríbé tó sóméóñé's ñótés{"]"}

# Hover text for dark mode toggle button
Switch_to_dark_mode_4dec = {"["}Swítçh tó dàrk módé{"]"}

# Hover text for light mode toggle button
Switch_to_light_mode_72ce = {"["}Swítçh tó líght módé{"]"}

# Button text to load blurred media
Tap_to_Load_4b05 = {"["}Tàp tó Lóàd{"]"}

# Message shown when Dave trial period has ended
The_Dave_Nostr_AI_assistant_trial_has_ended_____Thanks_for_testing__Zap-enabled_Dave_coming_soon_c6c7 = {"["}Thé Dàvé Ñóstr ÀÍ àssístàñt tríàl hàs éñdéd :(. Thàñks fór téstíñg! Zàp-éñàbléd Dàvé çómíñg sóóñ!{"]"}

# Label for theme, Appearance settings section
Theme_4aac = {"["}Thémé:{"]"}

# Column title for note thread view
Thread_0f20 = {"["}Thréàd{"]"}

# Link text for thread references
thread_ad1f = {"["}thréàd{"]"}

# Title for universe column
Universe_e01e = {"["}Úñívérsé{"]"}

# Column title for universe feed
Universe_ffaa = {"["}Úñívérsé{"]"}

# Checkbox label for using wallet only for current account
Use_this_wallet_for_the_current_account_only_61dc = {"["}Úsé thís wàllét fór thé çúrréñt àççóúñt óñly{"]"}

# Username and domain identification message
username___at___domain___will_be_used_for_identification_a4fd = {"["}"{$username}" àt "{$domain}" wíll bé úséd fór ídéñtífíçàtíóñ{"]"}

# Profile username field label
Username_daa7 = {"["}Úsérñàmé{"]"}

# Label for view folder button, Storage settings section
View_folder_9742 = {"["}Víéw fóldér:{"]"}

# Column title for wallet management
Wallet_5e50 = {"["}Wàllét{"]"}

# Hint for deck name input field
We_recommend_short_names_083e = {"["}Wé réçómméñd shórt ñàmés{"]"}

# Profile website field label
Website_7980 = {"["}Wébsíté{"]"}

# Placeholder for note input field
Write_a_banger_note_here_bad2 = {"["}Wríté à bàñgér ñóté héré...{"]"}

# Placeholder text for key input field
Your_key_here_81bd = {"["}Yóúr kéy héré...{"]"}

# Title for your notes column
Your_Notes_f6db = {"["}Yóúr Ñótés{"]"}

# Title for your notifications column
Your_Notifications_080d = {"["}Yóúr Ñótífíçàtíóñs{"]"}

# Heading for zap (tip) action
Zap_16b4 = {"["}Zàp{"]"}

# Hover text for zap button
Zap_this_note_42b2 = {"["}Zàp thís ñóté{"]"}

# Label for zoom level, Appearance settings section
Zoom_Level_29a8 = {"["}Zóóm Lévél:{"]"}

# Pluralized strings

# Search results count
Got__count__results_for___query_85fb =
    { $count ->
        [one] {"["}Gót {$count} résúlt fór '{$query}'{"]"}
       *[other] {"["}Gót {$count} résúlts fór '{$query}'{"]"}
    }
