#!/usr/bin/env bash

root_dir=$PWD

cargo ndk --target arm64-v8a -o ./crates/notedeck_chrome/android/app/src/main/jniLibs/ build --profile release

cd ./crates/notedeck_chrome/android

./gradlew build && ./gradlew installDebug

cd $root_dir