[package]
name = "notebook"
edition = "2024"
version.workspace = true

[dependencies]
nostrdb = { workspace = true }
enostr = { workspace = true }
nostr = { workspace = true }
serde_json = { workspace = true }
wordid = { workspace = true }
profiling = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
pollster = { workspace = true }
futures-util = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt", "rt-multi-thread"] }
