[package]
name = "agentium_cli"
edition = "2024"
version.workspace = true

[[bin]]
name = "agentium"
path = "src/main.rs"

[dependencies]
agentium-core = { workspace = true }
cli_term = { workspace = true }
nostrdb_net = { workspace = true }
enostr = { workspace = true }
nostrdb = { workspace = true }
hex = { workspace = true }
regex = "1"
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "time", "signal"] }

[target.'cfg(unix)'.dependencies]
libc = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread"] }
tempfile = { workspace = true }
bin_testing = { workspace = true }
bech32 = { workspace = true }
