# Main translation file for Notedeck
# This file contains common UI strings used throughout the application
# Auto-generated by extract_i18n.py - DO NOT EDIT MANUALLY

# Regular strings

# Profile about/bio field label
About_00c0 = About

# Column title for account management
Accounts_f018 = Accounts

# Button label to add a relay
Add_269d = Add

# Label for add column button
Add_47df = Add

# Button label to add a different wallet
Add_a_different_wallet_that_will_only_be_used_for_this_account_de8d = Add a different wallet that will only be used for this account

# Error message for missing wallet
Add_a_wallet_to_continue_d170 = Add a wallet to continue

# Button label to add a new account
Add_account_1cfc = Add account

# Column title for adding new account
Add_Account_d06c = Add Account

# Column title for adding algorithm column
Add_Algo_Column_0d75 = Add Algo Column

# Column title for adding new column
Add_Column_c764 = Add Column

# Column title for adding new deck
Add_Deck_fabf = Add Deck

# Column title for adding external notifications column
Add_External_Notifications_Column_41ae = Add External Notifications Column

# Column title for adding hashtag column
Add_Hashtag_Column_ebf4 = Add Hashtag Column

# Column title for adding last notes column
Add_Last_Notes_Column_bbad = Add Last Notes Column

# Tooltip text for adding a new deck button
Add_new_deck_f2fc = Add new deck

# Column title for adding notifications column
Add_Notifications_Column_79f8 = Add Notifications Column

# Button label to add a relay
Add_relay_269d = Add relay

# Button label to add a wallet
Add_Wallet_d1be = Add Wallet

# Title for algorithmic feeds column
Algo_2452 = Algo

# Description for algorithmic feeds column
Algorithmic_feeds_to_aid_in_note_discovery_d344 = Algorithmic feeds to aid in note discovery

# Label for zap amount input field
Amount_70f0 = Amount

# Label for appearance settings section
Appearance_4c7f = Appearance

# Button to send message to Dave AI assistant
Ask_b7f4 = Ask

# Placeholder text for Dave AI input field
Ask_dave_anything_33d1 = Ask dave anything...

# Profile banner URL field label
Banner_52ef = Banner

# Beta version label
BETA_8e5d = BETA

# Broadcast the note to all connected relays
Broadcast_fe43 = Broadcast

# Broadcast the note only to local network relays
Broadcast_Local_7e50 = Broadcast Local

# Button label to cancel an action
Cancel_ed3b = Cancel

# Label for cancel clear cache, Storage settings section
Cancel_fd8b = Cancel

# Label for clear cache button, Storage settings section
Clear_cache_dccb = Clear cache

# Hover text for editable zap amount
Click_to_edit_0414 = Click to edit

# Column title for note composition
Compose_Note_c094 = Compose Note

# Label for configure relays, settings section
Configure_relays_d156 = Configure relays

# Label for confirm clear cache, Storage settings section
Confirm_9d9d = Confirm

# Button label to confirm an action
Confirm_f8a6 = Confirm

# Status label for connected relay
Connected_f8cc = Connected

# Status label for connecting relay
Connecting_6b7e = Connecting...

# Title for contact list column
Contact_List_f85a = Contact List

# Column title for contact lists
Contacts_7533 = Contacts

# Column title for last notes per contact
Contacts__last_notes_3f84 = Contacts (last notes)

# Button label to copy logs
Copy_a688 = Copy

# Button to copy media link to clipboard
Copy_Link_dc7c = Copy Link

# Copy the unique note identifier to clipboard
Copy_Note_ID_6b45 = Copy Note ID

# Copy the raw note data in JSON format to clipboard
Copy_Note_JSON_9e4e = Copy Note JSON

# Tooltip text for copying npub to clipboard
Copy_npub_to_clipboard_c105 = Copy npub to clipboard

# Copy the author's public key to clipboard
Copy_Pubkey_9cc4 = Copy Pubkey

# Copy the text content of the note to clipboard
Copy_Text_f81c = Copy Text

# Relative time in days
count_d_b9be = {$count}d

# Relative time in hours
count_h_3ecb = {$count}h

# Relative time in minutes
count_m_b41e = {$count}m

# Relative time in months
count_mo_7aba = {$count}mo

# Relative time in seconds
count_s_aa26 = {$count}s

# Relative time in weeks
count_w_7468 = {$count}w

# Relative time in years
count_y_9408 = {$count}y

# Button to create a new account
Create_Account_6994 = Create Account

# Button label to create a new deck
Create_Deck_16b7 = Create Deck

# Column title for custom timelines
Custom_a69e = Custom

# Column title for zap amount customization
Customize_Zap_Amount_cfc4 = Customize Zap Amount

# Column title for support page
Damus_Support_27c0 = Damus Support

# Label for Theme Dark, Appearance settings section
Dark_85fe = Dark

# Label for deck name input field
Deck_name_cd32 = Deck name

# Label for decks section in side panel
DECKS_1fad = DECKS

# Label for default zap amount input
Default_amount_per_zap_399d = Default amount per zap:

# Name of the default deck feed
Default_Deck_fcca = Default Deck

# Button label to delete a deck
Delete_Deck_bb29 = Delete Deck

# Tooltip for deleting a column
Delete_this_column_8d5a = Delete this column

# Button label to delete a wallet
Delete_Wallet_d1d4 = Delete Wallet

# Profile display name field label
Display_name_f9d9 = Display name

# Domain identification message
domain___will_be_used_for_identification_b67e = "{$domain}" will be used for identification

# Button to indicate that the user is done going through the onboarding process.
Done_50dd = Done

# Column title for editing deck
Edit_Deck_4018 = Edit Deck

# Button label to edit a deck
Edit_Deck_fd93 = Edit Deck

# Button label to edit user profile
Edit_Profile_49e6 = Edit Profile

# Column title for profile editing
Edit_Profile_8ad4 = Edit Profile

# Placeholder for hashtag input field
Enter_the_desired_hashtags_here__for_multiple_space-separated_7a69 = Enter the desired hashtags here (for multiple space-separated)

# Placeholder for relay input field
Enter_the_relay_here_1c8b = Enter the relay here

# Hint text to prompt entering the user's public key.
Enter_the_user_s_key__npub__hex__nip05__here_650c = Enter the user's key (npub, hex, nip05) here...

# Label for key input field. Key can be public key (npub), private key (nsec), or Nostr address (NIP-05).
Enter_your_key_0fca = Enter your key

# Instructions for entering Nostr credentials
Enter_your_public_key__npub___nostr_address__e_g___address____or_private_key__nsec___You_must_enter_your_private_key_to_be_able_to_post__reply__etc_48e9 = Enter your public key (npub), nostr address (e.g. {$address}), or private key (nsec). You must enter your private key to be able to post, reply, etc.

# Label for find user button
Find_User_bd12 = Find User

# Label for font size, Appearance settings section
Font_size_dd73 = Font size:

# Title for hashtags column
Hashtags_f8e0 = Hashtags

# Title for Home column
Home_8c19 = Home

# Label for deck icon selection
Icon_b0ab = Icon

# Label for Image cache size, Storage settings section
Image_cache_size_3004 = Image cache size:

# Title for individual user column
Individual_b776 = Individual

# Error message for invalid zap amount
Invalid_amount_6630 = Invalid amount

# Error message for invalid key input
Invalid_key_4726 = Invalid key.

# Error message for invalid Nostr Wallet Connect URI
Invalid_NWC_URI_031b = Invalid NWC URI

# Zap amount button for 100000 sats. Abbreviated because the button is too small to display the full amount.
k_100K_686c = 100K

# Zap amount button for 10000 sats. Abbreviated because the button is too small to display the full amount.
k_10K_f7e6 = 10K

# Zap amount button for 20000 sats. Abbreviated because the button is too small to display the full amount.
k_20K_4977 = 20K

# Zap amount button for 50000 sats. Abbreviated because the button is too small to display the full amount.
k_50K_c2dc = 50K

# Zap amount button for 5000 sats. Abbreviated because the button is too small to display the full amount.
k_5K_f7e6 = 5K

# Description for your notes column
Keep_track_of_your_notes___replies_a334 = Keep track of your notes & replies

# label for keys setting section
Keys_435f = Keys

# Label for language, Appearance settings section
Language_e264 = Language:

# Title for last note per user column
Last_Note_per_User_17ad = Last Note per User

# Label for Theme Light, Appearance settings section
Light_7475 = Light

# Bitcoin Lightning network address field label
Lightning_network_address__lud16_ea51 = Lightning network address (lud16)

# Login page title
Login_9eef = Login

# Login button text
Login_now___let_s_do_this_5630 = Login now — let's do this!

# Text shown on blurred media from unfollowed users
Media_from_someone_you_don_t_follow_5611 = Media from someone you don't follow

# Tooltip for moving a column
Moves_this_column_to_another_position_0d4b = Moves this column to another position

# Title for the user's deck
My_Deck_4ac5 = My Deck

# reaction from user to a note you were tagged in
name__reacted_to_a_note_you_were_tagged_in_4b62 = {$name} reacted to a note you were tagged in

# reaction from user to your note
name__reacted_to_your_note_ead9 = {$name} reacted to your note

# repost from user
name__reposted_a_note_you_were_tagged_in_1379 = {$name} reposted a note you were tagged in

# repost from user
name__reposted_your_note_1379 = {$name} reposted your note

# Label asking if the user is new to Nostr. Underneath this label is a button to create an account.
New_to_Nostr_a2fd = New to Nostr?

# NIP-05 identity field label
Nostr_address__NIP-05_identity_74a2 = Nostr address (NIP-05 identity)

# Default username when profile is not available
nostrich_df29 = nostrich

# Status label for disconnected relay
Not_Connected_6292 = Not Connected

# Link text for note references
note_cad6 = note

# Beta product warning message
Notedeck_is_a_beta_product__Expect_bugs_and_contact_us_when_you_run_into_issues_a671 = Notedeck is a beta product. Expect bugs and contact us when you run into issues.

# Filter label for notes only view
Notes_03fb = Notes

# Label for notes-only filter
Notes_60d2 = Notes

# Filter label for notes and replies view
Notes___Replies_1ec2 = Notes & Replies

# Label for notes and replies filter
Notes___Replies_6e3b = Notes & Replies

# Column title for notifications
Notifications_d673 = Notifications

# Title for notifications column
Notifications_ef56 = Notifications

# Relative time for very recent events (less than 3 seconds)
now_2181 = now

# Setting to turn on sorting replies so that the newest are shown first
On_f412 = On

# Column title for finding users to follow
Onboarding_4a25 = Onboarding

# Button label to open email client
Open_Email_25e9 = Open Email

# Instruction to open email client
Open_your_default_email_client_to_get_help_from_the_Damus_team_68dc = Open your default email client to get help from the Damus team

# Label for others settings section
Others_7267 = Others

# Placeholder text for NWC URI input
Paste_your_NWC_URI_here_b471 = Paste your NWC URI here...

# Error message for missing deck name
Please_create_a_name_for_the_deck_38e7 = Please create a name for the deck.

# Error message for missing deck name and icon
Please_create_a_name_for_the_deck_and_select_an_icon_0add = Please create a name for the deck and select an icon.

# Error message for missing deck icon
Please_select_an_icon_655b = Please select an icon.

# Button label to post a note
Post_now_8a49 = Post now

# Instruction for copying logs
Press_the_button_below_to_copy_your_most_recent_logs_to_your_system_s_clipboard__Then_paste_it_into_your_email_322e = Press the button below to copy your most recent logs to your system's clipboard. Then paste it into your email.

# Profile picture URL field label
Profile_picture_81ff = Profile picture

# label describing public key
PUBLIC_ACCOUNT_ID_4394 = PUBLIC ACCOUNT ID

# Column title for quote composition
Quote_475c = Quote

# Error message when quote note cannot be found
Quote_of_unknown_note_e4f0 = Quote of unknown note

# Label for read-only profile mode
Read_only_82ff = Read only

# Column title for relay management
Relays_9d89 = Relays

# Label for relay list section
Relays_ad5e = Relays

# Column title for reply composition
Reply_3bf1 = Reply

# Hover text for reply button
Reply_to_this_note_f5de = Reply to this note

# Error message when reply note cannot be found
Reply_to_unknown_note_4401 = Reply to unknown note

# Fallback template for replying to user
replying_to__user_15ab = replying to {$user}

# Template for replying to user in unknown thread
replying_to__user__in_someone_s_thread_e148 = replying to {$user} in someone's thread

# Template for replying to note in different user's thread
replying_to__user__s__note__in__thread_user__s__thread_daa8 = replying to {$user}'s {$note} in {$thread_user}'s {$thread}

# Template for replying to user's note
replying_to__user__s__note_ccba = replying to {$user}'s {$note}

# Template for replying to root thread
replying_to__user__s__thread_444d = replying to {$user}'s {$thread}

# Fallback text when reply note is not found
replying_to_a_note_e0bc = replying to a note

# Hover text for repost button
Repost_this_note_8e56 = Repost this note

# Label for reposted notes
Reposted_61c8 = Reposted

# Label for reset note body font size, Appearance settings section
Reset_4e60 = Reset

# Label for reset zoom level, Appearance settings section
Reset_62d4 = Reset

# Heading for support section
Running_into_a_bug_1796 = Running into a bug?

# Label for satoshis (Bitcoin unit) for custom zap amount input field
SATS_45d7 = SATS

# Unit label for satoshis (Bitcoin unit) for configuring default zap amount in wallet settings.
sats_e5ec = sats

# Button to save default zap amount
Save_6f7c = Save

# Button label to save profile changes
Save_changes_00db = Save changes

# Column title for search page
Search_c573 = Search

# Placeholder for search notes input field
Search_notes_42a6 = Search notes...

# Search in progress message
Searching_for___query_5d18 = Searching for '{$query}'

# label describing secret key
SECRET_ACCOUNT_LOGIN_KEY_8440 = SECRET ACCOUNT LOGIN KEY

# Description for Home column
See_notes_from_your_contacts_ac16 = See notes from your contacts

# Description for universe column
See_the_whole_nostr_universe_7694 = See the whole nostr universe

# Button to select all profiles in follow pack
Select_All_a319 = Select All

# Button label to send a zap
Send_1ea4 = Send

# Column title for app settings
Settings_7a4f = Settings

# Description for last note per user column
Show_the_last_note_for_each_user_from_a_list_50e7 = Show the last note for each user from a list

# Button label to sign out of account
Sign_out_337b = Sign out

# Title for someone else's notes column
Someone_else_s_Notes_7e5f = Someone else's Notes

# Title for someone else's notifications column
Someone_else_s_Notifications_82e6 = Someone else's Notifications

# Label for Sort replies newest first, others settings section
Sort_replies_newest_first_b6c3 = Sort replies newest first:

# Description for contact list column
Source_the_last_note_for_each_user_in_your_contact_list_e157 = Source the last note for each user in your contact list

# Description for hashtags column
Stay_up_to_date_with_a_certain_hashtag_88e3 = Stay up to date with a certain hashtag

# Description for notifications column
Stay_up_to_date_with_notifications_and_mentions_6f4e = Stay up to date with notifications and mentions

# Description for someone else's notes column
Stay_up_to_date_with_someone_else_s_notes___replies_464c = Stay up to date with someone else's notes & replies

# Description for someone else's notifications column
Stay_up_to_date_with_someone_else_s_notifications_and_mentions_3473 = Stay up to date with someone else's notifications and mentions

# Description for individual user column
Stay_up_to_date_with_someone_s_notes___replies_aa78 = Stay up to date with someone's notes & replies

# Description for your notifications column
Stay_up_to_date_with_your_notifications_and_mentions_e73e = Stay up to date with your notifications and mentions

# Step 1 label in support instructions
Step_1_8656 = Step 1

# Step 2 label in support instructions
Step_2_d08d = Step 2

# Label for storage settings section
Storage_ed65 = Storage

# Column title for subscribing to external user
Subscribe_to_someone_else_s_notes_d1e9 = Subscribe to someone else's notes

# Column title for subscribing to individual user
Subscribe_to_someone_s_notes_b3c8 = Subscribe to someone's notes

# Support email address
Support_email_44d9 = Support email:

# Hover text for dark mode toggle button
Switch_to_dark_mode_4dec = Switch to dark mode

# Hover text for light mode toggle button
Switch_to_light_mode_72ce = Switch to light mode

# Button text to load blurred media
Tap_to_Load_4b05 = Tap to Load

# Message shown when Dave trial period has ended
The_Dave_Nostr_AI_assistant_trial_has_ended_____Thanks_for_testing__Zap-enabled_Dave_coming_soon_c6c7 = The Dave Nostr AI assistant trial has ended :(. Thanks for testing! Zap-enabled Dave coming soon!

# Label for theme, Appearance settings section
Theme_4aac = Theme:

# Column title for note thread view
Thread_0f20 = Thread

# Link text for thread references
thread_ad1f = thread

# Title for universe column
Universe_e01e = Universe

# Column title for universe feed
Universe_ffaa = Universe

# Checkbox label for using wallet only for current account
Use_this_wallet_for_the_current_account_only_61dc = Use this wallet for the current account only

# Username and domain identification message
username___at___domain___will_be_used_for_identification_a4fd = "{$username}" at "{$domain}" will be used for identification

# Profile username field label
Username_daa7 = Username

# Label for view folder button, Storage settings section
View_folder_9742 = View folder

# Column title for wallet management
Wallet_5e50 = Wallet

# Hint for deck name input field
We_recommend_short_names_083e = We recommend short names

# Profile website field label
Website_7980 = Website

# Placeholder for note input field
Write_a_banger_note_here_bad2 = Write a banger note here...

# Placeholder text for key input field
Your_key_here_81bd = Your key here...

# Title for your notes column
Your_Notes_f6db = Your Notes

# Title for your notifications column
Your_Notifications_080d = Your Notifications

# Heading for zap (tip) action
Zap_16b4 = Zap

# Hover text for zap button
Zap_this_note_42b2 = Zap this note

# Label for zoom level, Appearance settings section
Zoom_Level_29a8 = Zoom Level:

# Pluralized strings

# Search results count
Got__count__results_for___query_85fb =
    { $count ->
        [one] Got {$count} result for '{$query}'
       *[other] Got {$count} results for '{$query}'
    }


# amount of reactions a note you were tagged in received
name__and__count__others_reacted_to_a_note_you_were_tagged_in_181a =
    { $count ->
        [one] {$name} and {$count} other reacted to a note you were tagged in
       *[other] {$name} and {$count} others reacted to a note you were tagged in
    }


# describing the amount of reactions your note received
name__and__count__others_reacted_to_your_note_0f6a =
    { $count ->
        [one] {$name} and {$count} other reacted to your note
       *[other] {$name} and {$count} others reacted to your note
    }


# describing the amount of reposts a note you were tagged in received
name__and__count__others_reposted_a_note_you_were_tagged_in_08e1 =
    { $count ->
        [one] {$name} and {$count} other reposted a note you were tagged in
       *[other] {$name} and {$count} others reposted a note you were tagged in
    }


# describing the amount of reposts your note received
name__and__count__others_reposted_your_note_70a0 =
    { $count ->
        [one] {$name} and {$count} other reposted your note
       *[other] {$name} and {$count} others reposted your note
    }
