[package]
name = "headway_cli"
edition = "2024"
version.workspace = true

[[bin]]
name = "headway"
path = "src/main.rs"

[dependencies]
headway = { workspace = true }
nostrdb_net = { workspace = true }
enostr = { workspace = true }
nostrdb = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

[dev-dependencies]
nostrdb_relay = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "net"] }
tokio-tungstenite = { workspace = true }
futures-util = { workspace = true }
tempfile = { workspace = true }
bech32 = { workspace = true }
