# Main translation file for Notedeck
# This file contains common UI strings used throughout the application
# Auto-generated by extract_i18n.py - DO NOT EDIT MANUALLY


# Regular strings

# Profile about/bio field label
About_00c0 = 关于
# Column title for account management
Accounts_f018 = 帐户
# Button label to add a relay
Add_269d = 添加
# Label for add column button
Add_47df = 添加
# Button label to add a different wallet
Add_a_different_wallet_that_will_only_be_used_for_this_account_de8d = 添加一个仅用于此帐户的不同钱包
# Error message for missing wallet
Add_a_wallet_to_continue_d170 = 添加钱包以继续
# Button label to add a new account
Add_account_1cfc = 添加帐户
# Column title for adding new account
Add_Account_d06c = 添加帐户
# Column title for adding algorithm column
Add_Algo_Column_0d75 = 添加算法列
# Column title for adding new column
Add_Column_c764 = 添加列
# Column title for adding new deck
Add_Deck_fabf = 添加仪表板
# Column title for adding external notifications column
Add_External_Notifications_Column_41ae = 添加外部通知列
# Column title for adding hashtag column
Add_Hashtag_Column_ebf4 = 添加标签列
# Column title for adding last notes column
Add_Last_Notes_Column_bbad = 添加最新笔记列
# Column title for adding notifications column
Add_Notifications_Column_79f8 = 添加通知列
# Button label to add a relay
Add_relay_269d = 添加中继器
# Button label to add a wallet
Add_Wallet_d1be = 添加钱包
# Title for algorithmic feeds column
Algo_2452 = 算法
# Description for algorithmic feeds column
Algorithmic_feeds_to_aid_in_note_discovery_d344 = 用于帮助发现笔记的算法源
# Label for zap amount input field
Amount_70f0 = 金额
# Label for appearance settings section
Appearance_4c7f = 外观
# Button to send message to Dave AI assistant
Ask_b7f4 = 询问
# Placeholder text for Dave AI input field
Ask_dave_anything_33d1 = 向 Dave 提问任何问题…
# Profile banner URL field label
Banner_52ef = 横幅
# Beta version label
BETA_8e5d = BETA
# Option in settings section to show the source client label at the bottom of the note
Bottom_33c8 = 底部
# Broadcast the note to all connected relays
Broadcast_fe43 = 广播
# Broadcast the note only to local network relays
Broadcast_Local_7e50 = 仅广播至本地中继
# Button label to cancel an action
Cancel_ed3b = 取消
# Label for cancel clear cache, Storage settings section
Cancel_fd8b = 取消
# Label for clear cache button, Storage settings section
Clear_cache_dccb = 清除缓存
# Hover text for editable zap amount
Click_to_edit_0414 = 点击以编辑
# Column title for note composition
Compose_Note_c094 = 撰写笔记
# Label for configure relays, settings section
Configure_relays_d156 = 配置中继器
# Label for confirm clear cache, Storage settings section
Confirm_9d9d = 确认
# Button label to confirm an action
Confirm_f8a6 = 确认
# Status label for connected relay
Connected_f8cc = 已连接
# Status label for connecting relay
Connecting_6b7e = 正在连接...
# Title for contact list column
Contact_List_f85a = 联系人列表
# Column title for contact lists
Contacts_7533 = 联系人
# Column title for last notes per contact
Contacts__last_notes_3f84 = 联系人（最新笔记）
# Button label to copy logs
Copy_a688 = 复制
# Button to copy media link to clipboard
Copy_Link_dc7c = 复制链接
# Copy the unique note identifier to clipboard
Copy_Note_ID_6b45 = 复制笔记 ID
# Copy the raw note data in JSON format to clipboard
Copy_Note_JSON_9e4e = 复制笔记 JSON
# Copy the author's public key to clipboard
Copy_Pubkey_9cc4 = 复制公钥
# Copy the text content of the note to clipboard
Copy_Text_f81c = 复制文本
# Relative time in days
count_d_b9be = { $count }天
# Relative time in hours
count_h_3ecb = { $count }小时
# Relative time in minutes
count_m_b41e = { $count }分钟
# Relative time in months
count_mo_7aba = { $count }月
# Relative time in seconds
count_s_aa26 = { $count }秒
# Relative time in weeks
count_w_7468 = { $count }周
# Relative time in years
count_y_9408 = { $count }年
# Button to create a new account
Create_Account_6994 = 创建帐户
# Button label to create a new deck
Create_Deck_16b7 = 创建仪表板
# Column title for custom timelines
Custom_a69e = 自定义
# Column title for zap amount customization
Customize_Zap_Amount_cfc4 = 自定义打闪金额
# Column title for support page
Damus_Support_27c0 = 达摩支持
# Label for Theme Dark, Appearance settings section
Dark_85fe = 暗色
# Label for deck name input field
Deck_name_cd32 = 仪表板名称
# Label for decks section in side panel
DECKS_1fad = 仪表板
# Label for default zap amount input
Default_amount_per_zap_399d = 打闪默认金额：
# Name of the default deck feed
Default_Deck_fcca = 默认仪表板
# Button label to delete a deck
Delete_Deck_bb29 = 删除仪表板
# Tooltip for deleting a column
Delete_this_column_8d5a = 删除此列
# Button label to delete a wallet
Delete_Wallet_d1d4 = 删除钱包
# Profile display name field label
Display_name_f9d9 = 显示名称
# Domain identification message
domain___will_be_used_for_identification_b67e = "{ $domain }" 将用于身份识别
# Column title for editing deck
Edit_Deck_4018 = 编辑仪表板
# Button label to edit a deck
Edit_Deck_fd93 = 编辑仪表板
# Button label to edit user profile
Edit_Profile_49e6 = 编辑个人档案
# Column title for profile editing
Edit_Profile_8ad4 = 编辑个人档案
# Placeholder for hashtag input field
Enter_the_desired_hashtags_here__for_multiple_space-separated_7a69 = 在此输入所需的标签 (用于多个时以空格分隔)
# Placeholder for relay input field
Enter_the_relay_here_1c8b = 在此输入中继器
# Hint text to prompt entering the user's public key.
Enter_the_user_s_key__npub__hex__nip05__here_650c = 在此输入用户的密钥（npub、hex、nip05）...
# Label for key input field. Key can be public key (npub), private key (nsec), or Nostr address (NIP-05).
Enter_your_key_0fca = 请输入你的密钥
# Instructions for entering Nostr credentials
Enter_your_public_key__npub___nostr_address__e_g___address____or_private_key__nsec___You_must_enter_your_private_key_to_be_able_to_post__reply__etc_48e9 = 请输入你的公钥（npub）、nostr 地址（如 { $address }）、或私钥(nsec)。 你必须输入你的私钥才能发帖、回复等等。
# Label for find user button
Find_User_bd12 = 查找用户
# Title for hashtags column
Hashtags_f8e0 = 标签
# Option in settings section to hide the source client label in note display
Hide_281d = 隐藏
# Title for Home column
Home_8c19 = 主页
# Label for deck icon selection
Icon_b0ab = 图标
# Label for Image cache size, Storage settings section
Image_cache_size_3004 = 图像缓存大小：
# Title for individual user column
Individual_b776 = 个人
# Error message for invalid zap amount
Invalid_amount_6630 = 无效金额
# Error message for invalid key input
Invalid_key_4726 = 无效密钥。
# Error message for invalid Nostr Wallet Connect URI
Invalid_NWC_URI_031b = 无效 NWC URI
# Zap amount button for 100000 sats. Abbreviated because the button is too small to display the full amount.
k_100K_686c = 10万
# Zap amount button for 10000 sats. Abbreviated because the button is too small to display the full amount.
k_10K_f7e6 = 1万
# Zap amount button for 20000 sats. Abbreviated because the button is too small to display the full amount.
k_20K_4977 = 2万
# Zap amount button for 50000 sats. Abbreviated because the button is too small to display the full amount.
k_50K_c2dc = 5万
# Zap amount button for 5000 sats. Abbreviated because the button is too small to display the full amount.
k_5K_f7e6 = 5千
# Description for your notes column
Keep_track_of_your_notes___replies_a334 = 随时查看你的笔记和回复
# Label for language, Appearance settings section
Language_e264 = 语言：
# Title for last note per user column
Last_Note_per_User_17ad = 每个用户的最新笔记
# Label for Theme Light, Appearance settings section
Light_7475 = 亮色
# Bitcoin Lightning network address field label
Lightning_network_address__lud16_ea51 = 闪电网络地址（lud16）
# Login page title
Login_9eef = 登录
# Login button text
Login_now___let_s_do_this_5630 = 立即登录——让我们开始吧！
# Text shown on blurred media from unfollowed users
Media_from_someone_you_don_t_follow_5611 = 来自你不关注的用户的媒体
# Tooltip for moving a column
Moves_this_column_to_another_position_0d4b = 将此列移动到其他位置
# Title for the user's deck
My_Deck_4ac5 = 我的仪表板
# Label asking if the user is new to Nostr. Underneath this label is a button to create an account.
New_to_Nostr_a2fd = 第一次使用 Nostr？
# NIP-05 identity field label
Nostr_address__NIP-05_identity_74a2 = Nostr 地址 (NIP-05 标识符)
# Default username when profile is not available
nostrich_df29 = nostr 用户
# Status label for disconnected relay
Not_Connected_6292 = 未连接
# Link text for note references
note_cad6 = 笔记
# Beta product warning message
Notedeck_is_a_beta_product__Expect_bugs_and_contact_us_when_you_run_into_issues_a671 = Notedeck目前是测试版产品。可能会出现故障，如果遇到问题请及时联系我们。
# Filter label for notes only view
Notes_03fb = 笔记
# Label for notes-only filter
Notes_60d2 = 笔记
# Filter label for notes and replies view
Notes___Replies_1ec2 = 笔记和回复
# Label for notes and replies filter
Notes___Replies_6e3b = 笔记和回复
# Column title for notifications
Notifications_d673 = 通知
# Title for notifications column
Notifications_ef56 = 通知
# Relative time for very recent events (less than 3 seconds)
now_2181 = 刚刚
# Button label to open email client
Open_Email_25e9 = 打开电子邮箱
# Instruction to open email client
Open_your_default_email_client_to_get_help_from_the_Damus_team_68dc = 打开你的默认电子邮件客户端以获得达摩团队的帮助
# Label for others settings section
Others_7267 = 其它
# Placeholder text for NWC URI input
Paste_your_NWC_URI_here_b471 = 在此粘贴你的 NWC URI...
# Error message for missing deck name
Please_create_a_name_for_the_deck_38e7 = 请为仪表板创建一个名称。
# Error message for missing deck name and icon
Please_create_a_name_for_the_deck_and_select_an_icon_0add = 请为仪表板创建一个名称并选择一个图标。
# Error message for missing deck icon
Please_select_an_icon_655b = 请选择一个图标。
# Button label to post a note
Post_now_8a49 = 立即发布
# Instruction for copying logs
Press_the_button_below_to_copy_your_most_recent_logs_to_your_system_s_clipboard__Then_paste_it_into_your_email_322e = 请按下面的按钮将你最近的日志复制到系统剪贴板，然后将其粘贴到你的电子邮件。
# Profile picture URL field label
Profile_picture_81ff = 头像图片
# Column title for quote composition
Quote_475c = 引用
# Error message when quote note cannot be found
Quote_of_unknown_note_e4f0 = 引用未知笔记
# Label for read-only profile mode
Read_only_82ff = 只读
# Column title for relay management
Relays_9d89 = 中继器
# Label for relay list section
Relays_ad5e = 中继器
# Column title for reply composition
Reply_3bf1 = 回复
# Hover text for reply button
Reply_to_this_note_f5de = 回复此笔记
# Error message when reply note cannot be found
Reply_to_unknown_note_4401 = 回复未知笔记
# Fallback template for replying to user
replying_to__user_15ab = 正在回复{ $user }
# Template for replying to user in unknown thread
replying_to__user__in_someone_s_thread_e148 = 正在回复某人帖子中的{ $user }
# Template for replying to note in different user's thread
replying_to__user__s__note__in__thread_user__s__thread_daa8 = 正在回复在{ $thread_user }的{ $thread }中的{ $user }的{ $note }
# Template for replying to user's note
replying_to__user__s__note_ccba = 正在回复{ $user }的{ $note }
# Template for replying to root thread
replying_to__user__s__thread_444d = 正在回复{ $user }的{ $thread }
# Fallback text when reply note is not found
replying_to_a_note_e0bc = 正在回复笔记
# Hover text for repost button
Repost_this_note_8e56 = 转发此笔记
# Label for reposted notes
Reposted_61c8 = 已转发
# Label for reset zoom level, Appearance settings section
Reset_62d4 = 重置
# Heading for support section
Running_into_a_bug_1796 = 遇到故障了吗？
# Label for satoshis (Bitcoin unit) for custom zap amount input field
SATS_45d7 = 聪
# Unit label for satoshis (Bitcoin unit) for configuring default zap amount in wallet settings.
sats_e5ec = 聪
# Button to save default zap amount
Save_6f7c = 保存
# Button label to save profile changes
Save_changes_00db = 保存变更
# Column title for search page
Search_c573 = 搜索
# Placeholder for search notes input field
Search_notes_42a6 = 搜索笔记...
# Search in progress message
Searching_for___query_5d18 = 正在搜索'{ $query }'
# Description for Home column
See_notes_from_your_contacts_ac16 = 查看来自你的联系人的笔记
# Description for universe column
See_the_whole_nostr_universe_7694 = 查看整个 nostr 宇宙
# Button label to send a zap
Send_1ea4 = 发送
# Column title for app settings
Settings_7a4f = 设置
# Label for Show source client, others settings section
Show_source_client_9e31 = 显示来源客户端
# Description for last note per user column
Show_the_last_note_for_each_user_from_a_list_50e7 = 显示列表中每个用户的最新一条笔记
# Button label to sign out of account
Sign_out_337b = 登出
# Title for someone else's notes column
Someone_else_s_Notes_7e5f = 其他人的笔记
# Title for someone else's notifications column
Someone_else_s_Notifications_82e6 = 其他人的通知
# Description for contact list column
Source_the_last_note_for_each_user_in_your_contact_list_e157 = 获取你的联系人列表中每个用户的最新一条笔记
# Description for hashtags column
Stay_up_to_date_with_a_certain_hashtag_88e3 = 获取某个标签的最新动态
# Description for notifications column
Stay_up_to_date_with_notifications_and_mentions_6f4e = 获取通知和提及的最新动态
# Description for someone else's notes column
Stay_up_to_date_with_someone_else_s_notes___replies_464c = 获取其他用户的笔记和回复的最新动态
# Description for someone else's notifications column
Stay_up_to_date_with_someone_else_s_notifications_and_mentions_3473 = 获取其他用户的通知和提及的最新动态
# Description for individual user column
Stay_up_to_date_with_someone_s_notes___replies_aa78 = 获取某人的笔记和回复的最新动态
# Description for your notifications column
Stay_up_to_date_with_your_notifications_and_mentions_e73e = 获取你的通知和提及的最新动态
# Step 1 label in support instructions
Step_1_8656 = 第一步
# Step 2 label in support instructions
Step_2_d08d = 第二步
# Label for storage settings section
Storage_ed65 = 存储
# Column title for subscribing to external user
Subscribe_to_someone_else_s_notes_d1e9 = 订阅他人的笔记
# Column title for subscribing to individual user
Subscribe_to_someone_s_notes_b3c8 = 订阅某人的笔记
# Hover text for dark mode toggle button
Switch_to_dark_mode_4dec = 切换到暗色模式
# Hover text for light mode toggle button
Switch_to_light_mode_72ce = 切换到亮色模式
# Button text to load blurred media
Tap_to_Load_4b05 = 点击加载
# Message shown when Dave trial period has ended
The_Dave_Nostr_AI_assistant_trial_has_ended_____Thanks_for_testing__Zap-enabled_Dave_coming_soon_c6c7 = Dave Nostr AI 助手试用期已经结束 :(。感谢测试！可打闪付款的 Dave 即将来临！
# Label for theme, Appearance settings section
Theme_4aac = 主题：
# Column title for note thread view
Thread_0f20 = 帖子
# Link text for thread references
thread_ad1f = 帖子
# Option in settings section to show the source client label at the top of the note
Top_6aeb = 顶部
# Title for universe column
Universe_e01e = 宇宙
# Column title for universe feed
Universe_ffaa = 宇宙
# Checkbox label for using wallet only for current account
Use_this_wallet_for_the_current_account_only_61dc = 此钱包仅限用于当前帐户
# Username and domain identification message
username___at___domain___will_be_used_for_identification_a4fd = "{ $username }" 于 "{ $domain }" 将被用于身份识别
# Profile username field label
Username_daa7 = 用户名
# Label for view folder button, Storage settings section
View_folder_9742 = 查看文件夹：
# Column title for wallet management
Wallet_5e50 = 钱包
# Hint for deck name input field
We_recommend_short_names_083e = 我们推荐使用简短的名称
# Profile website field label
Website_7980 = 网站
# Placeholder for note input field
Write_a_banger_note_here_bad2 = 在这里写条超赞的笔记...
# Placeholder text for key input field
Your_key_here_81bd = 在此输入你的密钥...
# Title for your notes column
Your_Notes_f6db = 你的笔记
# Title for your notifications column
Your_Notifications_080d = 你的通知
# Heading for zap (tip) action
Zap_16b4 = 打闪
# Hover text for zap button
Zap_this_note_42b2 = 打闪此笔记
# Label for zoom level, Appearance settings section
Zoom_Level_29a8 = 缩放大小：

# Pluralized strings

# Search results count
Got__count__results_for___query_85fb =
    {
        $count ->
            [one] 查询"{ $query }"得到{ $count }条结果
           *[other] 查询"{ $query }"得到{ $count }条结果
    }
